/* Generated By:JJTree: Do not edit this line. ASTForInitBlocks.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package overwatchcode.parser;

public
class ASTForInitBlocks extends SimpleNode {
  public ASTForInitBlocks(int id) {
    super(id);
  }

  public ASTForInitBlocks(OWCParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public overwatchcode.workshop.Block jjtAccept(OWCParserVisitor visitor, overwatchcode.workshop.Block data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8c9895aae09a1b99b3aebd8de6c3cb0c (do not edit this line) */
