/* Generated By:JJTree: Do not edit this line. ASTForIncBlocks.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package overwatchcode.parser;

public
class ASTForIncBlocks extends SimpleNode {
  public ASTForIncBlocks(int id) {
    super(id);
  }

  public ASTForIncBlocks(OWCParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public overwatchcode.workshop.Block jjtAccept(OWCParserVisitor visitor, overwatchcode.workshop.Block data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e0fdda0602ad58d971ee3a48e05afad9 (do not edit this line) */
