/* Generated By:JJTree: Do not edit this line. ASTVarArrayItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package overwatchcode.parser;

public
class ASTVarArrayItem extends SimpleNode {
  public ASTVarArrayItem(int id) {
    super(id);
  }

  public ASTVarArrayItem(OWCParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public overwatchcode.workshop.Block jjtAccept(OWCParserVisitor visitor, overwatchcode.workshop.Block data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c07e6400eaa00ed7896bdb5a1f5190e2 (do not edit this line) */
