/* Generated By:JavaCC: Do not edit this line. OWCParserTreeConstants.java Version 5.0 */
package overwatchcode.parser;

public interface OWCParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTRULE = 1;
  public int JJTRULEEVENT = 2;
  public int JJTRULENAME = 3;
  public int JJTRULESCOPE = 4;
  public int JJTTEAMSCOPE = 5;
  public int JJTPLAYERSCOPE = 6;
  public int JJTRULECONDITION = 7;
  public int JJTLINESTATEMENT = 8;
  public int JJTSTATEMENT = 9;
  public int JJTFUNCTIONCALL = 10;
  public int JJTFUNCTIONNAME = 11;
  public int JJTARGUMENTS = 12;
  public int JJTVARNAME = 13;
  public int JJTARRAYITEM = 14;
  public int JJTCHAIN = 15;
  public int JJTFNARRAYITEM = 16;
  public int JJTVARARRAYITEM = 17;
  public int JJTASSIGNMENT = 18;
  public int JJTEXPRESSION = 19;
  public int JJTCONDITIONALOREXPRESSION = 20;
  public int JJTCONDITIONALANDEXPRESSION = 21;
  public int JJTRELATIONALEXPRESSION = 22;
  public int JJTRELATIONALOP = 23;
  public int JJTADDITIVEEXPRESSION = 24;
  public int JJTADDITIVEOP = 25;
  public int JJTMULTIPLICATIVEEXPRESSION = 26;
  public int JJTMULTIPLOCATIVEOP = 27;
  public int JJTUNARYEXPRESSION = 28;
  public int JJTVECTORCOMPONENT = 29;
  public int JJTVECTOR = 30;
  public int JJTNUMBER = 31;
  public int JJTBOOLEAN = 32;
  public int JJTSTRING = 33;
  public int JJTACTIONS = 34;
  public int JJTCONDITION = 35;
  public int JJTIF = 36;
  public int JJTELSE = 37;
  public int JJTLOOP = 38;
  public int JJTWHILE = 39;
  public int JJTFOR = 40;
  public int JJTFORINITBLOCKS = 41;
  public int JJTFORCONDITION = 42;
  public int JJTFORINCBLOCKS = 43;
  public int JJTBREAK = 44;
  public int JJTCONTINUE = 45;


  public String[] jjtNodeName = {
    "Start",
    "Rule",
    "RuleEvent",
    "RuleName",
    "RuleScope",
    "TeamScope",
    "PlayerScope",
    "RuleCondition",
    "LineStatement",
    "Statement",
    "FunctionCall",
    "FunctionName",
    "Arguments",
    "VarName",
    "ArrayItem",
    "Chain",
    "FnArrayItem",
    "VarArrayItem",
    "Assignment",
    "Expression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "RelationalExpression",
    "RelationalOp",
    "AdditiveExpression",
    "AdditiveOp",
    "MultiplicativeExpression",
    "MultiplocativeOp",
    "UnaryExpression",
    "VectorComponent",
    "Vector",
    "Number",
    "Boolean",
    "String",
    "Actions",
    "Condition",
    "If",
    "Else",
    "Loop",
    "While",
    "For",
    "ForInitBlocks",
    "ForCondition",
    "ForIncBlocks",
    "Break",
    "Continue",
  };
}
/* JavaCC - OriginalChecksum=058b035aae2758da3c469ac130960405 (do not edit this line) */
