/* Generated By:JavaCC: Do not edit this line. OWCParserVisitor.java Version 5.0 */
package overwatchcode.parser;

public interface OWCParserVisitor
{
  public overwatchcode.workshop.Block visit(SimpleNode node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTStart node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTRule node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTRuleEvent node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTRuleName node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTRuleScope node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTTeamScope node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTPlayerScope node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTRuleCondition node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTStatement node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTFunctionCall node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTFunctionName node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTArguments node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTVarName node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTArrayItem node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTChain node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTFnArrayItem node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTVarArrayItem node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTAssignment node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTExpression node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTConditionalOrExpression node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTConditionalAndExpression node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTRelationalExpression node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTRelationalOp node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTAdditiveExpression node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTAdditiveOp node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTMultiplicativeExpression node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTMultiplocativeOp node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTUnaryExpression node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTVectorComponent node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTVector node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTNumber node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTBoolean node, overwatchcode.workshop.Block data);
  public overwatchcode.workshop.Block visit(ASTString node, overwatchcode.workshop.Block data);
}
/* JavaCC - OriginalChecksum=ce573423ad580e8763d259ba02424e30 (do not edit this line) */
