/* Generated By:JavaCC: Do not edit this line. OWCParserTreeConstants.java Version 5.0 */
package overwatchcode.parser;

public interface OWCParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTRULE = 1;
  public int JJTRULEEVENT = 2;
  public int JJTRULENAME = 3;
  public int JJTRULESCOPE = 4;
  public int JJTTEAMSCOPE = 5;
  public int JJTPLAYERSCOPE = 6;
  public int JJTRULECONDITION = 7;
  public int JJTSTATEMENT = 8;
  public int JJTFUNCTIONCALL = 9;
  public int JJTFUNCTIONNAME = 10;
  public int JJTARGUMENTS = 11;
  public int JJTVARNAME = 12;
  public int JJTARRAYITEM = 13;
  public int JJTCHAIN = 14;
  public int JJTFNARRAYITEM = 15;
  public int JJTVARARRAYITEM = 16;
  public int JJTASSIGNMENT = 17;
  public int JJTEXPRESSION = 18;
  public int JJTCONDITIONALOREXPRESSION = 19;
  public int JJTCONDITIONALANDEXPRESSION = 20;
  public int JJTRELATIONALEXPRESSION = 21;
  public int JJTRELATIONALOP = 22;
  public int JJTADDITIVEEXPRESSION = 23;
  public int JJTADDITIVEOP = 24;
  public int JJTMULTIPLICATIVEEXPRESSION = 25;
  public int JJTMULTIPLOCATIVEOP = 26;
  public int JJTUNARYEXPRESSION = 27;
  public int JJTVECTORCOMPONENT = 28;
  public int JJTVECTOR = 29;
  public int JJTNUMBER = 30;
  public int JJTBOOLEAN = 31;
  public int JJTSTRING = 32;


  public String[] jjtNodeName = {
    "Start",
    "Rule",
    "RuleEvent",
    "RuleName",
    "RuleScope",
    "TeamScope",
    "PlayerScope",
    "RuleCondition",
    "Statement",
    "FunctionCall",
    "FunctionName",
    "Arguments",
    "VarName",
    "ArrayItem",
    "Chain",
    "FnArrayItem",
    "VarArrayItem",
    "Assignment",
    "Expression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "RelationalExpression",
    "RelationalOp",
    "AdditiveExpression",
    "AdditiveOp",
    "MultiplicativeExpression",
    "MultiplocativeOp",
    "UnaryExpression",
    "VectorComponent",
    "Vector",
    "Number",
    "Boolean",
    "String",
  };
}
/* JavaCC - OriginalChecksum=0cc2d07db5f843083473ba4e12b55003 (do not edit this line) */
