/* Generated By:JJTree&JavaCC: Do not edit this line. OWCParserConstants.java */
package overwatchcode.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OWCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER_LITERAL = 4;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 5;
  /** RegularExpression Id. */
  int TRUE = 6;
  /** RegularExpression Id. */
  int FALSE = 7;
  /** RegularExpression Id. */
  int STRING_LITERAL = 8;
  /** RegularExpression Id. */
  int SCOPE_ALL = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int FOREACH = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int GT = 15;
  /** RegularExpression Id. */
  int GTEQ = 16;
  /** RegularExpression Id. */
  int ST = 17;
  /** RegularExpression Id. */
  int STEQ = 18;
  /** RegularExpression Id. */
  int EQ = 19;
  /** RegularExpression Id. */
  int NEQ = 20;
  /** RegularExpression Id. */
  int NOT_OP = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "<NUMBER_LITERAL>",
    "<BOOLEAN_LITERAL>",
    "\"true\"",
    "\"false\"",
    "<STRING_LITERAL>",
    "\"?\"",
    "\"if\"",
    "\"for\"",
    "\"while\"",
    "\"foreach\"",
    "<IDENTIFIER>",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"!\"",
    "\"{\"",
    "\";\"",
    "\"}\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"$\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"->X\"",
    "\"->Y\"",
    "\"->Z\"",
  };

}
